name: Org PR Checks
on:
  pull_request:
    branches: [main, develop] # Aplica a las ramas principales

permissions:
  contents: read
  pull-requests: read

jobs:
  commitlint:
    name: Commit message lint (PR)
    uses: Jack-s-Cave/.github/.github/workflows/commitlint-on-pr.yml@main
    with:
      strict: true
      check_pr_title: true
