
name: Validar ramas de PR

# Controls when the workflow will run
on:
  pull_request:
    types: [opened, reopened, synchronize]


jobs:
  validar-rama:
    name: Validar origen del PR según rama destino
    runs-on: ubuntu-latest
    steps:
      - name: Verificar origen y destino del PR
        run: |
          echo "🔎 Validando PR..."
          echo "Destino: ${{ github.event.pull_request.base.ref }}"
          echo "Origen: ${{ github.event.pull_request.head.ref }}"

          DESTINO="${{ github.event.pull_request.base.ref }}"
          ORIGEN="${{ github.event.pull_request.head.ref }}"

          # Validaciones
          if [[ "$DESTINO" == "main" && ! "$ORIGEN" =~ ^(release|hotfix)/ ]]; then
            echo "❌ No se permite hacer PR a 'main' desde '$ORIGEN'. Solo se permite desde 'release/*' o 'hotfix/*'."
            exit 1
          fi

          if [[ "$DESTINO" == "develop" && ! "$ORIGEN" =~ ^(feature|release)/ ]]; then
            echo "❌ No se permite hacer PR a 'develop' desde '$ORIGEN'. Solo se permite desde 'feature/*' o 'release/*'."
            exit 1
          fi

          echo "✅ Pull request válido. Puede continuar."
